version: 2
jobs:
  build:
    working_directory: /dockerapp
    docker:
      - image: docker:20.10.21
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache py-pip=22.3.1
            pip install docker-compose==1.15.0
      - run:
          name: Run tests
          command: |
            docker-compose up -d --build
            docker-compose run dockerapp python test.py
